### ISSUE TITLE
Allow removing the OTP devices of other users as admin

### ISSUE THREAD

**Issue by mvantellingen** [LabD/wagtail-2fa#3]
In wagtail you should be able to unregister otp devices for users when they lost the register otp device

**Comment by colink-eb** [comment]
Was this closed because the change was implemented or because it was decided this would not be done? I've updated to the version released on this date, and from what I see, the link in user administration more managing a user's 2fa devices is gone completely, although I've found that it is this possible for a user to update their own devices through their profile settings.

Am I missing some configuration or workflow that allows the ability for someone to remove someone else's 2fa device?

**Comment by commadelimited** [comment]
I'm experiencing this issue as well. It would be awesome if there were a way to remove the devices of other users. We've got about 30 people using our instance of Wagtail and we get requests to reset their devices probably once or twice a month.
